### ISSUE TITLE
能详细说一下如何运行的吗

### ISSUE THREAD

**Issue by lygl** [wangruns/Hybrid-Music-Recommender-System#1]
放到我的idea上无法运行，运用主函数吗

**Comment by taroballs** [comment]
我的也是 我的idea也无法运行 会出现bug：无法执行selectAll方法
现在正在换版本调试

**Comment by Guomoon** [comment]
up主，求个联系方式

**Comment by wangruns** [comment]
这是一个web app的源码，需要先安装好README.md里面说的开发工具Eclipse，数据库MySQL，配置管理工具Maven，服务器Tomcat，以及JDK。然后需要将项目里面的sql数据文件导入你自己的数据库中，修改项目数据库配置文件（把数据库帐号密码修改为你自己的）。如果是在Eclipse中的话，导入项目，右键“run on server”应该就可以运行了。

**Comment by Guomoon** [comment]
大哥，求个联系方式qq啥的都行，有偿使用。毕设

**Comment by wangruns** [comment]
...主页有邮箱

**Comment by dongdongyu** [comment]
### The error may involve top.wangruns.trackstacking.dao.UserDao.selectAll
### The error occurred while executing a query
大佬好,我捯饬你这个项目一晚上了,用了idea,也用了eclipse,在idea中,能运行起来跳到主页,但是不管点哪一个按钮都会报这种类似的错,在eclipse中,也报这个,网上说mybatis的xml文件有问题,但是真找不到你问题在哪里,改来改去还是改回去了.你这个项目真的能正常运行么,求解啊

**Comment by Ross666666** [comment]
> 我的也是 我的idea也无法运行 会出现bug：无法执行selectAll方法
> 现在正在换版本调试

我也遇到同样的问题，请问你解决了吗？

**Comment by wangruns** [comment]
把你的配置详细的说一下 @dongdongyu

**Comment by dongdongyu** [comment]
> 把你的配置详细的说一下 @dongdongyu
我的配置环境：win7+mysql5.7.25+eclipse oxygen+jdk1.8 +tomcat7+maven3.1.1
报的错：
严重: Servlet.service() for servlet [springmvc] in context with path [/trackstacking] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [E:\bhbgj\.metadata\.plugins\org.eclipse.wst.server.core\tmp1\wtpwebapps\track-stacking\WEB-INF\classes\top\wangruns\trackstacking\dao\impl\UserDaoImpl.xml]
### The error may involve top.wangruns.trackstacking.dao.UserDao.selectByUser
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!] with root cause
com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.

**Comment by dongdongyu** [comment]
> > 我的也是 我的idea也无法运行 会出现bug：无法执行selectAll方法
> > 现在正在换版本调试
> 
> 我也遇到同样的问题，请问你解决了吗？ @taroballs @dongdongyu

暂时还没有

**Comment by wangruns** [comment]
这个应该是数据连接的问题. Windows用户，在连接数据配置文件jdbc.url后面加一句&serverTimezone=GMT

**Comment by dongdongyu** [comment]
> 这个应该是数据连接的问题. Windows用户，在连接数据配置文件jdbc.url后面加一句&serverTimezone=GMT

大佬这个是正解~，我的运行成功了，不报错了噢，谢谢啦~

**Comment by dongdongyu** [comment]
> > 我的也是 我的idea也无法运行 会出现bug：无法执行selectAll方法
> > 现在正在换版本调试
> 
> 我也遇到同样的问题，请问你解决了吗？ @taroballs @dongdongyu

已经解决了，你看 @wangruns 的回答

**Comment by Ross666666** [comment]
> > > 我的也是 我的idea也无法运行 会出现bug：无法执行selectAll方法
> > > 现在正在换版本调试
> > 
> > 
> > 我也遇到同样的问题，请问你解决了吗？ @taroballs @dongdongyu
> 
> 已经解决了，你看 @wangruns 的回答

我的也运行起来了，多谢啦 @wangruns @dongdongyu

**Comment by yangchuan1234** [comment]
你好， 我引用了你的前端代码，后端代码是自己写的，bootstrap框架我也重新从网上下载，可是在运行时候tomcat不报错，弹出无法启动应用程序窗口，点击详细信息如下
（PS:Graduation_Project是我自己的项目名）
	* 激活 http://localhost:8080/Graduation_Project/ 导致异常。 检测到下列失败消息:
		+ 从 http://localhost:8080/Graduation_Project/ 读取清单时出现异常: 清单可能无效，或者文件无法打开。
		+ 根级别上的数据无效。 第 1 行，位置 1。
